import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
// import OwlCarousel from "react-owl-carousel";

import img1 from "../statics/img/item-1.jpg";
import img2 from "../statics/img/item-2.jpg";
import img3 from "../statics/img/item-3.jpg";

import icon1 from "../statics/img/icon-1.png";
import icon2 from "../statics/img/icon-2.png";
import icon3 from "../statics/img/icon-3.png";
import icon4 from "../statics/img/icon-4.png";

// import body_bg from "../statics/img/body-bg.png";
// import OwlCarousel from "react-owl-carousel";
// import "owl.carousel/dist/assets/owl.carousel.css";
// import "owl.carousel/dist/assets/owl.theme.default.css";
import bgwrap1 from "../statics/img/bgwrap-1.png";
import bgwrap2 from "../statics/img/bgwrap-2.png";
import { homeLabel } from "../labels/HomeLabel";

import { useRouter } from "next/dist/client/router";

const Bound = styled.div`
    .main-title-index {
        font-weight: 300;
    }
    .session-5 {
        .features-content {
            background: #132e5e;
            color: #fff;
            height: 100%;
        }
    }
    .btn-book {
        color: #ffffff;
        background-color: #132e5e;
        border-color: #132e5e;
        border-radius: 0;
        padding: 24px 30px;
        cursor: pointer;
        &:hover {
            background-color: #000000;
            border-color: #000000;
            color: #fff;
        }
    }
    .btn-explose {
        color: #aa8844;
        background-color: #f8f8f8;
        border-color: #f8f8f8;
        border-radius: 0;
        padding: 24px 30px;
        cursor: pointer;
        &:hover {
            color: #aa8844;
            background-color: #dfdfdf;
            border-color: #d9d9d9;
        }
    }
    .carousel-caption {
        color: #fff;
        background: #132e5e;
        top: 5%;
        right: 5%;
        left: unset;
        text-align: unset;
        height: 85%;
        width: 42%;
        padding: 30px 34px;
        h5 {
            color: #888888;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
    }
`;
export default function Home(props) {
    const router = useRouter();
    const { locale } = router;
    console.log(homeLabel(locale));
    return (
        <Bound>
            <Head>
                <title>Minh Brocker</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="session-1 mt-2">
                <div className="container">
                    <h1 className="main-title-index">
                        {homeLabel(locale).Introduce.title}
                    </h1>
                    <p>{homeLabel(locale).Introduce.content}</p>
                    <div
                        className="btn-group gap-2"
                        role="group"
                        aria-label="Basic example"
                    >
                        <a
                            href="https://outlook.office365.com/owa/calendar/MinhHoInsuranceBroker@minhhobroker.com/bookings/"
                            target="_blank"
                            rel="noreferrer"
                        >
                            <button type="button" className="btn btn-book">
                                {homeLabel(locale).Introduce.btnBook}
                            </button>
                        </a>
                        <a href="#my-experiend">
                            <button type="button" className="btn btn-explose">
                                {homeLabel(locale).Introduce.btnExplore}
                            </button>
                        </a>
                    </div>
                </div>
            </div>

            <div className="session-2 mt-3">
                <div className="container-fluid">
                    <div
                        id="carouselExampleCaptions"
                        className="carousel slide"
                        data-bs-ride="carousel"
                    >
                        <div className="carousel-indicators">
                            <button
                                type="button"
                                data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="0"
                                className="active"
                                aria-current="true"
                                aria-label="Slide 1"
                            ></button>
                            <button
                                type="button"
                                data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="1"
                                aria-label="Slide 2"
                            ></button>
                            <button
                                type="button"
                                data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="2"
                                aria-label="Slide 3"
                            ></button>
                        </div>
                        <div className="carousel-inner">
                            <div className="carousel-item active">
                                <Image
                                    src={img1}
                                    alt="img1"
                                    className="d-block w-100"
                                />
                                <div className="carousel-caption d-none d-md-block">
                                    <h5>{homeLabel(locale).Slide1.title}</h5>
                                    <p>{homeLabel(locale).Slide1.p_1}</p>
                                    <p>{homeLabel(locale).Slide1.p_2}</p>
                                </div>
                            </div>
                            <div className="carousel-item">
                                <Image
                                    src={img2}
                                    alt="img1"
                                    className="d-block w-100"
                                />

                                <div className="carousel-caption d-none d-md-block">
                                    <h5>{homeLabel(locale).Slide2.title}</h5>
                                    <p>{homeLabel(locale).Slide2.p_1}</p>
                                    <p>{homeLabel(locale).Slide2.p_2}</p>
                                </div>
                            </div>
                            <div className="carousel-item">
                                <Image
                                    src={img3}
                                    alt="img1"
                                    className="d-block w-100"
                                />

                                <div className="carousel-caption d-none d-md-block">
                                    <h5>{homeLabel(locale).Slide3.title}</h5>
                                    <p>{homeLabel(locale).Slide3.p_1}</p>
                                    <p>{homeLabel(locale).Slide3.p_2}</p>
                                </div>
                            </div>
                        </div>
                        <button
                            className="carousel-control-prev"
                            type="button"
                            data-bs-target="#carouselExampleCaptions"
                            data-bs-slide="prev"
                        >
                            <span
                                className="carousel-control-prev-icon"
                                aria-hidden="true"
                            ></span>
                            <span className="visually-hidden">Previous</span>
                        </button>
                        <button
                            className="carousel-control-next"
                            type="button"
                            data-bs-target="#carouselExampleCaptions"
                            data-bs-slide="next"
                        >
                            <span
                                className="carousel-control-next-icon"
                                aria-hidden="true"
                            ></span>
                            <span className="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
            </div>

            <div className="session-3 mt-3" id="my-experiend">
                <div className="container">
                    <div className="title-wrap">
                        <div className="sub-heading">
                            <span>{homeLabel(locale).OurService.title}</span>
                        </div>
                        <h2>{homeLabel(locale).OurService.content}</h2>
                    </div>
                </div>
            </div>

            <div className="session-4 mt-3">
                <div className="container">
                    <div className="row">
                        <div
                            className="col-sm-6 col-md-3"
                            style={{ minHeight: "344px" }}
                        >
                            <div className="img-icon text-center">
                                <Image src={icon1} alt="icon1" />
                            </div>
                            <h4>{homeLabel(locale).OurServiceBlock1.title}</h4>
                            <p>{homeLabel(locale).OurServiceBlock1.p_1}</p>
                        </div>
                        <div
                            className="col-sm-6 col-md-3"
                            style={{ minHeight: "344px" }}
                        >
                            <div className="img-icon text-center">
                                <Image src={icon2} alt="icon2" />
                            </div>
                            <h4>{homeLabel(locale).OurServiceBlock2.title}</h4>
                            <p>{homeLabel(locale).OurServiceBlock2.p_1}</p>
                        </div>
                        <div
                            className="col-sm-6 col-md-3"
                            style={{ minHeight: "344px" }}
                        >
                            <div className="img-icon  text-center">
                                <Image src={icon3} alt="icon2" />
                            </div>
                            <h4>{homeLabel(locale).OurServiceBlock3.title}</h4>
                            <p>{homeLabel(locale).OurServiceBlock3.p_1}</p>
                        </div>
                        <div
                            className="col-sm-6 col-md-3"
                            style={{ minHeight: "344px" }}
                        >
                            <div className="img-icon text-center">
                                <Image src={icon4} alt="icon2" />
                            </div>
                            <h4>{homeLabel(locale).OurServiceBlock4.title}</h4>
                            <p>{homeLabel(locale).OurServiceBlock4.p_1}</p>
                        </div>

                        <div
                            className="col-sm-6 col-md-3"
                            style={{ minHeight: "344px" }}
                        >
                            <div className="img-icon  text-center">
                                <Image src={icon4} alt="icon2" />
                            </div>
                            <h4>{homeLabel(locale).OurServiceBlock5.title}</h4>
                            <p>{homeLabel(locale).OurServiceBlock5.p_1}</p>
                        </div>

                        <div
                            className="col-sm-6 col-md-3"
                            style={{ minHeight: "344px" }}
                        >
                            <div className="img-icon text-center">
                                <Image src={icon4} alt="icon2" />
                            </div>
                            <h4>{homeLabel(locale).OurServiceBlock6.title}</h4>
                            <p>{homeLabel(locale).OurServiceBlock6.p_1}</p>
                        </div>
                    </div>
                </div>
            </div>
        </Bound>
    );
}
