import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import img1 from "../statics/img/item-1.jpg";
import img2 from "../statics/img/item-2.jpg";
import img3 from "../statics/img/item-3.jpg";

import icon1 from "../statics/img/icon-1.png";
import icon2 from "../statics/img/icon-2.png";
import icon3 from "../statics/img/icon-3.png";
import icon4 from "../statics/img/icon-4.png";

import bgwrap1 from "../statics/img/bgwrap-1.png";
import bgwrap2 from "../statics/img/bgwrap-2.png";
import { homeLabel } from "../labels/HomeLabel";

import { useRouter } from "next/dist/client/router";

const Bound = styled.div`
    .session-5 {
        .features-content {
            background: #132e5e;
            color: #fff;
            height: 100%;
        }
    }
`;
export default function Home(props) {
    const router = useRouter();
    const { locale } = router;
    console.log(homeLabel(locale));
    return (
        <Bound>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="session-1 mt-2">
                <div className="container">
                    <h1>{homeLabel(locale).Introduce.title}</h1>
                    <p>{homeLabel(locale).Introduce.content}</p>
                    <div
                        className="btn-group gap-2"
                        role="group"
                        aria-label="Basic example"
                    >
                        <button type="button" className="btn btn-primary">
                            {homeLabel(locale).Introduce.btnBook}
                        </button>

                        <button type="button" className="btn btn-primary">
                            {homeLabel(locale).Introduce.btnExplore}
                        </button>
                    </div>
                </div>
            </div>

            <div className="session-2 mt-3">
                <div className="container-fluid">
                    <div
                        id="carouselExampleCaptions"
                        className="carousel slide"
                        data-bs-ride="carousel"
                    >
                        <div className="carousel-indicators">
                            <button
                                type="button"
                                data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="0"
                                className="active"
                                aria-current="true"
                                aria-label="Slide 1"
                            ></button>
                            <button
                                type="button"
                                data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="1"
                                aria-label="Slide 2"
                            ></button>
                            <button
                                type="button"
                                data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="2"
                                aria-label="Slide 3"
                            ></button>
                        </div>
                        <div className="carousel-inner">
                            <div className="carousel-item active">
                                <Image
                                    src={img1}
                                    alt="img1"
                                    className="d-block w-100"
                                />
                                <div className="carousel-caption d-none d-md-block">
                                    <h5>{homeLabel(locale).Slide1.title}</h5>
                                    <p>{homeLabel(locale).Slide1.p_1}</p>
                                    <p>{homeLabel(locale).Slide1.p_2}</p>
                                </div>
                            </div>
                            <div className="carousel-item">
                                <Image
                                    src={img2}
                                    alt="img1"
                                    className="d-block w-100"
                                />

                                <div className="carousel-caption d-none d-md-block">
                                    <h5>{homeLabel(locale).Slide2.title}</h5>
                                    <p>{homeLabel(locale).Slide2.p_1}</p>
                                    <p>{homeLabel(locale).Slide2.p_2}</p>
                                </div>
                            </div>
                            <div className="carousel-item">
                                <Image
                                    src={img3}
                                    alt="img1"
                                    className="d-block w-100"
                                />

                                <div className="carousel-caption d-none d-md-block">
                                    <h5>{homeLabel(locale).Slide3.title}</h5>
                                    <p>{homeLabel(locale).Slide3.p_1}</p>
                                    <p>{homeLabel(locale).Slide3.p_2}</p>
                                </div>
                            </div>
                        </div>
                        <button
                            className="carousel-control-prev"
                            type="button"
                            data-bs-target="#carouselExampleCaptions"
                            data-bs-slide="prev"
                        >
                            <span
                                className="carousel-control-prev-icon"
                                aria-hidden="true"
                            ></span>
                            <span className="visually-hidden">Previous</span>
                        </button>
                        <button
                            className="carousel-control-next"
                            type="button"
                            data-bs-target="#carouselExampleCaptions"
                            data-bs-slide="next"
                        >
                            <span
                                className="carousel-control-next-icon"
                                aria-hidden="true"
                            ></span>
                            <span className="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
            </div>

            <div className="session-3 mt-3">
                <div className="container">
                    <div className="title-wrap">
                        <div className="sub-heading">
                            <span>{homeLabel(locale).OurService.title}</span>
                        </div>
                        <h2>{homeLabel(locale).OurService.content}</h2>
                    </div>
                </div>
            </div>

            <div className="session-4 mt-3">
                <div className="container">
                    <div className="row">
                        <div
                            className="col-sm-6 col-md-3"
                            style={{ minHeight: "344px" }}
                        >
                            <div className="img-icon">
                                <Image src={icon1} alt="icon1" />
                            </div>
                            <h4>{homeLabel(locale).OurServiceBlock1.title}</h4>
                            <p>{homeLabel(locale).OurServiceBlock1.p_1}</p>
                        </div>
                        <div
                            className="col-sm-6 col-md-3"
                            style={{ minHeight: "344px" }}
                        >
                            <div className="img-icon">
                                <Image src={icon2} alt="icon2" />
                            </div>
                            <h4>{homeLabel(locale).OurServiceBlock2.title}</h4>
                            <p>{homeLabel(locale).OurServiceBlock2.p_1}</p>
                        </div>
                        <div
                            className="col-sm-6 col-md-3"
                            style={{ minHeight: "344px" }}
                        >
                            <div className="img-icon">
                                <Image src={icon3} alt="icon2" />
                            </div>
                            <h4>{homeLabel(locale).OurServiceBlock3.title}</h4>
                            <p>{homeLabel(locale).OurServiceBlock3.p_1}</p>
                        </div>
                        <div
                            className="col-sm-6 col-md-3"
                            style={{ minHeight: "344px" }}
                        >
                            <div className="img-icon">
                                <Image src={icon4} alt="icon2" />
                            </div>
                            <h4>{homeLabel(locale).OurServiceBlock4.title}</h4>
                            <p>{homeLabel(locale).OurServiceBlock4.p_1}</p>
                        </div>

                        <div
                            className="col-sm-6 col-md-3"
                            style={{ minHeight: "344px" }}
                        >
                            <div className="img-icon">
                                <Image src={icon4} alt="icon2" />
                            </div>
                            <h4>{homeLabel(locale).OurServiceBlock5.title}</h4>
                            <p>{homeLabel(locale).OurServiceBlock5.p_1}</p>
                        </div>

                        <div
                            className="col-sm-6 col-md-3"
                            style={{ minHeight: "344px" }}
                        >
                            <div className="img-icon">
                                <Image src={icon4} alt="icon2" />
                            </div>
                            <h4>{homeLabel(locale).OurServiceBlock6.title}</h4>
                            <p>{homeLabel(locale).OurServiceBlock6.p_1}</p>
                        </div>
                    </div>
                </div>
            </div>

            <div className="session-5 mt-3">
                <div className="container-fluid" style={{ height: "1945px" }}>
                    <iframe
                        src="https://outlook.office365.com/owa/calendar/MinhHoInsuranceBroker@minhhobroker.com/bookings/"
                        width="100%"
                        height="100%"
                        scrolling="yes"
                        style={{ border: 0 }}
                    ></iframe>
                </div>
            </div>
        </Bound>
    );
}
